controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    turret_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    turret_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

turret_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - Horizontal_Joint
      - Vertical_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    gains:
      Horizontal_Joint: {p: 100.0, i: 0.1, d: 10.0}
      Vertical_Joint: {p: 100.0, i: 0.1, d: 10.0}

turret_velocity_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - Horizontal_Joint
      - Vertical_Joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
    gains:
      Horizontal_Joint: {p: 100.0, i: 0.1, d: 10.0}
      Vertical_Joint: {p: 100.0, i: 0.1, d: 10.0}

